// Set constraints for the video stream
var constraints = { video: { facingMode: "user" }, audio: false };
// Define constants
const cameraView = document.querySelector("#camera--view"),
    cameraOutput = document.querySelector("#camera--output"),
    cameraSensor = document.querySelector("#camera--sensor"),
    cameraTrigger = document.querySelector("#camera--trigger")
// Access the device camera and stream to cameraView
function cameraStart() {
    navigator.mediaDevices
        .getUserMedia(constraints)
        .then(function(stream) {
        track = stream.getTracks()[0];
        cameraView.srcObject = stream;
    })
    .catch(function(error) {
        console.error("Oops. Something is broken.", error);
    });
}
// Take a picture when cameraTrigger is tapped
cameraTrigger.onclick = function() {
    cameraSensor.width = cameraView.videoWidth;
    cameraSensor.height = cameraView.videoHeight;
    cameraSensor.getContext("2d").drawImage(cameraView, 0, 0);
    cameraOutput.src = cameraSensor.toDataURL("image/webp");
    cameraOutput.classList.add("taken");
	var access_token ='eyJhbGciOiJSUzI1NiIsImprdSI6Imh0dHBzOi8vaTMyODI0N3RyaWFsLmF1dGhlbnRpY2F0aW9uLmV1MTAuaGFuYS5vbmRlbWFuZC5jb20vdG9rZW5fa2V5cyIsImtpZCI6ImtleS1pZC0xIiwidHlwIjoiSldUIn0.eyJqdGkiOiJlZjNmNzkwNDZiZTE0YWU1ODY3MzU3NjI0MDMwNjA4OSIsImV4dF9hdHRyIjp7ImVuaGFuY2VyIjoiWFNVQUEiLCJ6ZG4iOiJpMzI4MjQ3dHJpYWwiLCJzZXJ2aWNlaW5zdGFuY2VpZCI6IjlmYTdmNGEwLWE3ZWQtNDQ2ZS04NjQ2LTgyZTY5YmYyYzdmNCJ9LCJzdWIiOiJzYi05ZmE3ZjRhMC1hN2VkLTQ0NmUtODY0Ni04MmU2OWJmMmM3ZjQhYjE1NzM3fGZvdW5kYXRpb24tc3RkLW1sZnRyaWFsIWIzNDEwIiwiYXV0aG9yaXRpZXMiOlsidWFhLnJlc291cmNlIiwiZm91bmRhdGlvbi1zdGQtbWxmdHJpYWwhYjM0MTAucmV0cmFpbnNlcnZpY2UucmVhZCIsImZvdW5kYXRpb24tc3RkLW1sZnRyaWFsIWIzNDEwLm1vZGVsc2VydmljZS5yZWFkIiwiZm91bmRhdGlvbi1zdGQtbWxmdHJpYWwhYjM0MTAubW9kZWxtZXRlcmluZy5yZWFkIiwiZm91bmRhdGlvbi1zdGQtbWxmdHJpYWwhYjM0MTAubW9kZWxyZXBvLndyaXRlIiwiZm91bmRhdGlvbi1zdGQtbWxmdHJpYWwhYjM0MTAucmVzb3VyY2VwbGFuc2VydmljZS5hbGwiLCJmb3VuZGF0aW9uLXN0ZC1tbGZ0cmlhbCFiMzQxMC5tb2RlbGRlcGxveW1lbnQuYWxsIiwiZm91bmRhdGlvbi1zdGQtbWxmdHJpYWwhYjM0MTAubWVoLmFsbCIsImZvdW5kYXRpb24tc3RkLW1sZnRyaWFsIWIzNDEwLm1vZGVscmVwby5yZWFkIiwiZm91bmRhdGlvbi1zdGQtbWxmdHJpYWwhYjM0MTAucmV0cmFpbnNlcnZpY2Uud3JpdGUiLCJmb3VuZGF0aW9uLXN0ZC1tbGZ0cmlhbCFiMzQxMC5mdW5jdGlvbmFsc2VydmljZS5hbGwiLCJmb3VuZGF0aW9uLXN0ZC1tbGZ0cmlhbCFiMzQxMC5kYXRhbWFuYWdlbWVudC53cml0ZSIsImZvdW5kYXRpb24tc3RkLW1sZnRyaWFsIWIzNDEwLmRhdGFtYW5hZ2VtZW50LnJlYWQiLCJmb3VuZGF0aW9uLXN0ZC1tbGZ0cmlhbCFiMzQxMC5zdG9yYWdlYXBpLmFsbCJdLCJzY29wZSI6WyJ1YWEucmVzb3VyY2UiLCJmb3VuZGF0aW9uLXN0ZC1tbGZ0cmlhbCFiMzQxMC5yZXRyYWluc2VydmljZS5yZWFkIiwiZm91bmRhdGlvbi1zdGQtbWxmdHJpYWwhYjM0MTAubW9kZWxzZXJ2aWNlLnJlYWQiLCJmb3VuZGF0aW9uLXN0ZC1tbGZ0cmlhbCFiMzQxMC5tb2RlbG1ldGVyaW5nLnJlYWQiLCJmb3VuZGF0aW9uLXN0ZC1tbGZ0cmlhbCFiMzQxMC5tb2RlbHJlcG8ud3JpdGUiLCJmb3VuZGF0aW9uLXN0ZC1tbGZ0cmlhbCFiMzQxMC5yZXNvdXJjZXBsYW5zZXJ2aWNlLmFsbCIsImZvdW5kYXRpb24tc3RkLW1sZnRyaWFsIWIzNDEwLm1vZGVsZGVwbG95bWVudC5hbGwiLCJmb3VuZGF0aW9uLXN0ZC1tbGZ0cmlhbCFiMzQxMC5tZWguYWxsIiwiZm91bmRhdGlvbi1zdGQtbWxmdHJpYWwhYjM0MTAubW9kZWxyZXBvLnJlYWQiLCJmb3VuZGF0aW9uLXN0ZC1tbGZ0cmlhbCFiMzQxMC5yZXRyYWluc2VydmljZS53cml0ZSIsImZvdW5kYXRpb24tc3RkLW1sZnRyaWFsIWIzNDEwLmZ1bmN0aW9uYWxzZXJ2aWNlLmFsbCIsImZvdW5kYXRpb24tc3RkLW1sZnRyaWFsIWIzNDEwLmRhdGFtYW5hZ2VtZW50LndyaXRlIiwiZm91bmRhdGlvbi1zdGQtbWxmdHJpYWwhYjM0MTAuZGF0YW1hbmFnZW1lbnQucmVhZCIsImZvdW5kYXRpb24tc3RkLW1sZnRyaWFsIWIzNDEwLnN0b3JhZ2VhcGkuYWxsIl0sImNsaWVudF9pZCI6InNiLTlmYTdmNGEwLWE3ZWQtNDQ2ZS04NjQ2LTgyZTY5YmYyYzdmNCFiMTU3Mzd8Zm91bmRhdGlvbi1zdGQtbWxmdHJpYWwhYjM0MTAiLCJjaWQiOiJzYi05ZmE3ZjRhMC1hN2VkLTQ0NmUtODY0Ni04MmU2OWJmMmM3ZjQhYjE1NzM3fGZvdW5kYXRpb24tc3RkLW1sZnRyaWFsIWIzNDEwIiwiYXpwIjoic2ItOWZhN2Y0YTAtYTdlZC00NDZlLTg2NDYtODJlNjliZjJjN2Y0IWIxNTczN3xmb3VuZGF0aW9uLXN0ZC1tbGZ0cmlhbCFiMzQxMCIsImdyYW50X3R5cGUiOiJjbGllbnRfY3JlZGVudGlhbHMiLCJyZXZfc2lnIjoiOWNkYzhkYWIiLCJpYXQiOjE1NTk1NDE4NzYsImV4cCI6MTU1OTU4NTA3NiwiaXNzIjoiaHR0cDovL2kzMjgyNDd0cmlhbC5sb2NhbGhvc3Q6ODA4MC91YWEvb2F1dGgvdG9rZW4iLCJ6aWQiOiIwOWE3NzczMS1iMGMyLTQ5MDEtOTFmMC1mMmZmNzkzYmRjOGUiLCJhdWQiOlsiZm91bmRhdGlvbi1zdGQtbWxmdHJpYWwhYjM0MTAucmV0cmFpbnNlcnZpY2UiLCJmb3VuZGF0aW9uLXN0ZC1tbGZ0cmlhbCFiMzQxMC5yZXNvdXJjZXBsYW5zZXJ2aWNlIiwiZm91bmRhdGlvbi1zdGQtbWxmdHJpYWwhYjM0MTAubWVoIiwiZm91bmRhdGlvbi1zdGQtbWxmdHJpYWwhYjM0MTAuZnVuY3Rpb25hbHNlcnZpY2UiLCJmb3VuZGF0aW9uLXN0ZC1tbGZ0cmlhbCFiMzQxMC5kYXRhbWFuYWdlbWVudCIsImZvdW5kYXRpb24tc3RkLW1sZnRyaWFsIWIzNDEwLm1vZGVsbWV0ZXJpbmciLCJ1YWEiLCJzYi05ZmE3ZjRhMC1hN2VkLTQ0NmUtODY0Ni04MmU2OWJmMmM3ZjQhYjE1NzM3fGZvdW5kYXRpb24tc3RkLW1sZnRyaWFsIWIzNDEwIiwiZm91bmRhdGlvbi1zdGQtbWxmdHJpYWwhYjM0MTAubW9kZWxyZXBvIiwiZm91bmRhdGlvbi1zdGQtbWxmdHJpYWwhYjM0MTAubW9kZWxkZXBsb3ltZW50IiwiZm91bmRhdGlvbi1zdGQtbWxmdHJpYWwhYjM0MTAuc3RvcmFnZWFwaSIsImZvdW5kYXRpb24tc3RkLW1sZnRyaWFsIWIzNDEwLm1vZGVsc2VydmljZSJdfQ.Uf-zhYQ7FPxDf7r4SNNqDYITHX4pkV2ZSoDrVTac5akNGg6fRjgCh8jsaEJaSCFTPFBFq_vEHGrku2JJzs-Kst1ayW83QPYJ4CEAEsCc_x0UMSbZrtBAGPkqoTZ7XwXsliQaITue8jxM4kmrL5zalDUzxnwyeLt_MO6w8bHPHl0MhOH_vIvQTDoNXwtDiLvARWqjvs_VXmX2ScaG1KwWvkHAfSnBb91rQh6wDKXTEhEzL4nieYYnVAzzZIYxeUkLlbpfI0ZGUWg6qhAod4DEa808rpr5D89P_lw38xLlX32bB7YOLysiuWiDgMyho_QXtlB80qTOcINf84fZy3nFSfifKeUkWUFo55VQ9OX5Ziaq9feoLTUslDfg15bfAE0pl4HqE9MX5HACtI7AbcZJmmnv2poTM91v68ZHhuDw6RQOIRwmr6yxNOFR7avtp9f3yyj3RsOeVZIMdXx1bpWjxcXVVH3K7ObtNvAqCLFoDElhRNW2yEGi5P44bIjfvLsL_C3od-qe10-cGopOTpRaoQwZT0f6FfaA3yNgsXyGRbDjoN2EAtOCUwsZlSyksOqTroL8NYQH6CucvHL26VK21xCfAFJETPCVUO9Jhd-TK88Ks9Ui_sCrt61EYwIVRQp7pfw9YLDvYSCOhwcYWRpxr2WfNZAvXlM_gCdBRqMyB0Q';
	jQuery.ajax( {
    url: 'https://i328247trial_trial-dev-byom.cfapps.eu10.hana.ondemand.com/model1',
    type: 'POST',
    data: { file: cameraOutput },
    beforeSend : function( xhr ) {
        xhr.setRequestHeader( "Authorization", "BEARER " + access_token );
    },
    success: function( response ) {
        // response
    }
} );
};
// Start the video stream when the window loads
window.addEventListener("load", cameraStart, false);
